### ISSUE TITLE
Indy module migration

### ISSUE THREAD

**Issue by SylvainJuge** [open-telemetry/opentelemetry-java-instrumentation#11457]
The following instrumentation modules currently override the `io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule#isIndyModule` and return `false`.

Each of them will need to be modified in order to become "indy compliant".

This is part of #8999 

- [x] documentation: indy modules and migration process: #11546 
- [x] akka.akka-http-10.0 #12243 
- [x] aws-sdk/aws-sdk-1.11 #11552
- [x] elasticsearch/elasticsearch-api-client-7.16 #11554 
- [x] elasticsearch/elasticsearch-rest-7.0 #11554 
- [x] executors #11738
- [x] finagglehttp #11559
- [x] hibernate/hibernate-4.0 #11553 
- [x] hibernate/hibernate-6.0 #11553 
- [x] hibernate/hibernate-procedure-call-4.3 #11553 
- [x] influxdb #11710
- [x] internal/internal-class-loader.javaagent-integration-tests.main
  - #12195 (failed)
  - #12242
- [x] internal/internal-class-loader 
  - #12195 (failed)
  - #12242
- [x] internal/internal-reflection #12136
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-jersey-2.0 #12432
- [x] kotlinx-coroutines/kotlinx-coroutines-1.0 
    #11578
- [x] netty.netty-4.1 #11559
- [x] opentelemetry-api/opentelemetry-api-1.0 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.10 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.15 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.27 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.31 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.32 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.37 
    #11578
- [x] opentelemetry-api/opentelemetry-api-1.4 
    #11578
- [x] opentelemetry-extension-kotlin-1.0 
    #11578
- [x] opentelemetry-instrumentation-api 
    #11578
- [x] pekko/pekko-http-1.0 #12428
- [x] ratpack/ratpack-1.4 #11559
- [x] reactor/reactor-3.1 
    #11578
- [x] rmi #12585 
- [x] servlet/servlet-3.0 #12432
- [x] spring/spring-webflux/spring-webflux-5.0 #11559
- [x] spring/spring-webmvc/spring-webmvc-3.1 #12432
- [x] spring/spring-webmvc/spring-webmvc-6.0 #12432
- [x] internal/internal-lambda + leftovers #13074

The #9508 PR provides a list of reasons why those instrumentations need to be manually modified, for reference this #9508 PR is also the one that introduced a toggle to test this dispatch implementation through modification of advice classes.

The PRs that are tagged "test indy" ([list](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=label%3A%22test+indy%22+)) will run with this automatic migration to "indy dispatch".
The automatic transformation is provided by `io.opentelemetry.javaagent.tooling.instrumentation.indy.AdviceTransformer` ASM transformer.

------

### Implementation proposal

This issue gather the steps to complete the 1st step of this "simple but tedious" plan:

1. migrate the instrumentation listed above
1. migrate all the instrumentations that are supported by `AdviceTransformer`
2. remove `AdviceTransformer` and cleanup

**Comment by SylvainJuge** [comment]
Because the migration will take a while, I have documented the migration and some of the characteristics of the non-inlined advices in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11546

The summary is:
- all instrumentation modules listed here are explicitly opting-out of automatic indy advice conversion
- those instrumentation modules need refactoring to become "indy compatible" with automatic advice conversion
- this issue tracks the global progress of this refactoring

Once everything has been migrated, this issue can be closed and we can start the next steps which might look like the following (to be further discussed):
- changing the default of `otel.javaagent.experimental.indy` configuration to `true` to perserve the ability to revert to inlining
- migrate all instrumentations to make them "indy native", mostly by adding `inline = false`
- implement further refactoring enabled by indy advices: remove shading, simplify helper classes, ...

**Comment by SylvainJuge** [comment]
After 8 months, we can finally consider this step as complete, so I'll close it 🎉.

The next steps are now described in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/13031
