### ISSUE TITLE
Database semantic convention stability implementation tracking issue

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#12608]
Database semantic convention stability implementation tracking issue

- [x] #11575
- [x] #12601
- [ ] Use `OTEL_SEMCONV_RC_OPT_IN` instead of `OTEL_SEMCONV_STABILITY_OPT_IN` until database semconv is actually marked stable to avoid confusion(?)
- [ ] #12602 
- [ ] #12605
- [ ] Implement the `db.client.operation.duration` metric
- [ ] Implement the `error.type` and `db.response.status_code` attributes
- [ ] Implement the `db.query.summary` attribute (requires updating the jflex sql parsing)
- [ ] Don't capture `db.operation.name` and `db.collection.name` when parsing (maybe, pending semconv PR)
- [ ] Implement `db.operation.batch.size`
- [ ] [we use lettuce built in tracing and that uses `db.namespace`, should we map it to `db.name` when using old semconv? This attribute is only generated by the latest lettuce](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12552#discussion_r1825665917)
- [ ] https://github.com/open-telemetry/semantic-conventions/pull/1560
- [ ] Upstream experimental `db.namespace` definitions to semconv repo for all of the supported instrumentations

**Comment by zeitlinger** [comment]
@trask @laurit which of these items are ready to be implemented?

**Comment by trask** [comment]
I think most of them, would love your help, pick any and DM me or post on [#otel-semconv-db-client-stability](https://cloud-native.slack.com/archives/C06HH05KNMC) with any questions!

**Comment by zeitlinger** [comment]
OK, I'll try https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12802

**Comment by stevesea** [comment]
is there already a ticket for correcting the units in the hikaricp instrumentation? 

in the current agent (2.13.1), hikaricp instrumentation for db.client.connections.{create_time,wait_time,use_time) implements the 1.24.0 semconv and units are 'ms'

1.30.0 semconv changes the units to 's'

**Comment by trask** [comment]
thanks @stevesea! I've added this to the list above

**Comment by jeanbisutti** [comment]
Perhaps some `Objects.requireNonNull` could be added to fail faster and limit the stack trace size in case of `null` argument:

```java
public OkHttpTelemetryBuilder setCapturedRequestHeaders(Collection<String> requestHeaders) {
  Objects.requireNonNull(requestHeaders, "requestHeaders");
  builder.setCapturedRequestHeaders(requestHeaders);
  return this;
}

public ApacheHttpClientTelemetryBuilder addAttributesExtractor(
    AttributesExtractor<ApacheHttpClientRequest, HttpResponse> attributesExtractor) {
  Objects.requireNonNull(attributesExtractor, "attributesExtractor");
  builder.addAttributesExtractor(attributesExtractor);
  return this;
}

public JavaHttpClientTelemetryBuilder setSpanNameExtractor(
    UnaryOperator<SpanNameExtractor<HttpRequest>> spanNameExtractorTransformer) {
  Objects.requireNonNull(spanNameExtractorTransformer, "spanNameExtractorTransformer");
  builder.setSpanNameExtractor(spanNameExtractorTransformer);
  return this;
}
```

**Comment by jeanbisutti** [comment]
For convenience, alternative methods with a varargs could perhaps be added. For example:

```java
setCapturedRequestHeaders(String... requestHeaders)

setCapturedResponseHeaders(String... responseHeaders)

setKnownMethods(String... knownMethods)`
```

**Comment by zeitlinger** [comment]
@trask can this be closed?
