### ISSUE TITLE
Replace hardcoded strings with API constants

### ISSUE THREAD

**Issue by vadeg** [open-telemetry/opentelemetry-java-instrumentation#1458]
This is a follow up ticket after making #1375. There are a lot of hardcoded strings, e.g. `"net.peer.ip"`, `"net.transport"` used in different places. It would be nice to use constants instead of them.

## Tasks

- [ ] Replace all `net.*` constants (#1459)
- [ ] Replace all `enduser.*` constants (#1459)
- [ ] Replace all `http.*` constants 
- [ ] Replace all `peer.*` constants 
- [ ] Replace all `rpc.*` constants (#1459)
- [ ] Replace all `message.*` constants
- [ ] Replace all `db.*` constants
- [ ] Replace all `messaging.*` constants
- [ ] Replace all `exception.*` constants
- [ ] Replace all `faas.*` constants

**Comment by iNikem** [comment]
Thank you for taking this! 🙏
