### ISSUE TITLE
More module / tracer renaming suggestions

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#163]
Shorten names where there is no ambiguity
- [x] aws-java-sdk-1.11 ⇒ aws-sdk-1.11 (#207)
- [x] aws-java-sdk-2.2 ⇒ aws-sdk-2.2 (#207)
- [x] datastax-cassandra-3.0 ⇒ cassandra-3.0 (#207)
- [x] jax-rs-annotations-1.0 ⇒ jaxrs-1.0 (#208)
- [x] jax-rs-annotations-2.0 ⇒ jaxrs-2.0 (#208)
- [x] reactor-core-3.1 ⇒ reactor-3.1 (#207)

For child modules, use standalone names, so we don't have to concatenate them with parent module to create tracer name (which allows us to simplify tracer names, e.g. `servlet-2.3` instead of `servlet-request-2.3`)
- [x] elasticsearch:rest-5.0 ⇒ elasticsearch:elasticsearch-rest-5.0 (#221)
- [x] elasticsearch:rest-6.4 ⇒ elasticsearch:elasticsearch-rest-6.4 (#221)
- [x] elasticsearch:transport-2.0 ⇒ elasticsearch:elasticsearch-transport-2.0 (#221)
- [x] elasticsearch:transport-5.0 ⇒ elasticsearch:elasticsearch-transport-5.0 (#221)
- [x] elasticsearch:transport-5.3 ⇒ elasticsearch:elasticsearch-transport-5.3 (#221)
- [x] elasticsearch:transport-6.0 ⇒ elasticsearch:elasticsearch-transport-6.0 (#221)
- [x] hibernate:core-3.3 ⇒ hibernate:hibernate-3.3 (#205)
- [x] hibernate:core-4.0 ⇒ hibernate:hibernate-4.0 (#205)
- [x] hibernate:core-4.3 ⇒ hibernate:hibernate-4.3 (#205)
- [x] mongo:driver-3.1 ⇒ mongo:mongo-3.1 (#206)
- [x] mongo:driver-3.7 ⇒ mongo:mongo-3.7 (#206)
- [x] mongo:driver-async-3.3 ⇒ mongo:mongo-async-3.3 (#206)
- [x] servlet:request-2.3 ⇒ servlet:servlet-2.3
- [x] servlet:request-3.0 ⇒ servlet:servlet-3.0

Maybe move common parent modules to "-common" submodule, e.g.
- [x] elasticsearch ⇒ elasticsearch:elasticsearch-common (#221)
- [x] hibernate ⇒ hibernate:hibernate-common (#205)
- [x] mongo ⇒ mongo:mongo-common (#206)
- [x] servlet ⇒ servlet:servlet-common (maybe not this instrumentation is possibly controversial?)

Also, missed this testing module earlier
- [x] cdi-1.2 ⇒ cdi-testing (#207)

Still TBD
- [x] java-class-loader ⇒ java-classloader

A couple more ideas after documenting these on the README:
- [x] rabbitmq-amqp ⇒ rabbitmq (there is no other client)
- [x] sparkjava ⇒ spark-web-framework (avoid confusion with Apache Spark)
- [ ] ~~spring-web-mvc ⇒ spring-servlet-mvc~~

**Comment by iNikem** [comment]
`spring-web-mvc` seems to be like official name, or even just `spring-mvc`. The other one is then `spring-webflux`. From https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#spring-web:

> Spring Web MVC is the original web framework built on the Servlet API and has been included in the Spring Framework from the very beginning. The formal name, “Spring Web MVC,” comes from the name of its source module (spring-webmvc), but it is more commonly known as “Spring MVC”.

> Parallel to Spring Web MVC, Spring Framework 5.0 introduced a reactive-stack web framework whose name, “Spring WebFlux,” is also based on its source module (spring-webflux).

**Comment by trask** [comment]
👍 to keeping the existing `spring-webmvc`, which matches the spring artifact name

**Comment by iNikem** [comment]
As `servlet-common` has been taken care of, can we close this issue now, @trask ?

**Comment by trask** [comment]
Yes! 🎉
