### ISSUE TITLE
Convert all instrumentation to the new Instrumenter API 

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2713]
Tracking/discussion issue for converting new instrumentation to the Instrumenter API defined in #2596.

Please add your name next to any that you are working on to avoid duplication. If you don't ability to update this comment, please comment below and someone will update it (you don't need to wait until someone updates the comment to work on it).

- [x] akka-http-10.0 #4359
- [ ] apache-camel-2.20
- [x] apache-dubbo/apache-dubbo-2.7 #4059
- [x] apache-httpasyncclient-4.1 #3490
- [x] apache-httpclient/apache-httpclient-2.0 #3012
- [x] apache-httpclient/apache-httpclient-4.0 #3042
- [x] apache-httpclient/apache-httpclient-5.0 #3062
- [x] armeria-1.3 #2596
- [x] async-http-client/async-http-client-1.9 #3794
- [x] async-http-client/async-http-client-2.0 #3211
- [x] aws-lambda-1.0 #4362
- [x] aws-sdk/aws-sdk-1.11 #4315
- [x] aws-sdk/aws-sdk-2.2 #4341
- [x] cassandra/cassandra-3.0 #3066
- [x] cassandra/cassandra-4.0 #3126
- [x] couchbase/couchbase-2.0 #3802
- [x] dropwizard-views-0.7 #3784
- [x] elasticsearch/elasticsearch-rest-common #4153
- [x] elasticsearch/elasticsearch-transport-common #4252
- [x] external-annotations #3738 #4578
- [x] finatra-2.9 #4495 
- [x] geode-1.4 #3067
- [x] google-http-client-1.19 #3932
- [x] grails-3.0 #3795
- [x] grizzly-2.0 #4409
- [x] grpc-1.6 #3073
- [x] gwt-2.0 #3146
- [x] hibernate/hibernate-common #4369
- [x] http-url-connection #4044
- [x] hystrix-1.4 #3802
- [x] java-http-client #3790
- [x] jaxrs-client/jaxrs-client-1.1 #3934
- [x] jaxrs-client/jaxrs-client-2.0/jaxrs-client-2.0-common #3938
- [x] jaxrs-client/jaxrs-client-2.0/jaxrs-client-2.0-resteasy-3.0 #3938
- [x] jaxrs/jaxrs-1.0 #3797
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-common #3796 
- [x] jaxws/jaxws-2.0-axis2-1.6 #3842
- [x] jaxws/jaxws-2.0-cxf-3.0 #3842
- [x] jaxws/jaxws-2.0-metro-2.2 #3842
- [x] jaxws/jaxws-common #3842
- [x] jdbc #2739 and #3160
- [x] jedis/jedis-1.4 #3064
- [x] jedis/jedis-3.0 #3124
- [x] jetty/jetty-11.0 #4078
- [x] jetty/jetty-8.0 #4078
- [x] jms-1.1 #2803
- [x] jsf/jsf-common #3838
- [x] jsf/mojarra-1.2 #3838
- [x] jsf/myfaces-1.2 #3838
- [x] jsp-2.3 #4257
- [x] kafka-clients-0.11 #3883
- [x] kafka-streams-0.11 #4140 
- [x] kubernetes-client-7.0 #4036 
- [x] lettuce/lettuce-4.0 #3068
- [x] lettuce/lettuce-5.0 #3125
- [x] liberty/liberty #4205
- [x] liberty/liberty-dispatcher #4256
- [x] methods #3070
- [x] mongo/mongo-3.1 #4387
- [x] netty/netty-3.8 #4368
- [x] netty/netty-4.0 #4342
- [x] netty/netty-4.1 #4342
- [x] okhttp/okhttp-2.2 #3852
- [x] okhttp/okhttp-3.0 #3538
- [x] opentelemetry-annotations-1.0 #3738
- [x] opentelemetry-api-1.0
- [x] play-ws/play-ws-common #3944
- [x] play/play-2.4 #4853
- [x] play/play-2.6 #4853
- [x] rabbitmq-2.7 #4463
- [x] ratpack-1.4 #4399
- [x] reactor-netty/reactor-netty-1.0 #4493
- [x] rediscala-1.8 #4152
- [x] redisson-3.0 #3069
- [x] rmi #4579
- [x] rocketmq-client-4.8 #4457
- [x] servlet/servlet-2.2 #4078
- [x] servlet/servlet-3.0 #4078
- [x] servlet/servlet-5.0 #4078
- [x] servlet/servlet-common #4078
- [x] servlet/servlet-javax-common #4078
- [x] spring/spring-batch-3.0 #4029
- [x] spring/spring-boot-autoconfigure #3607
- [x] spring/spring-data-1.8 #3991
- [x] spring/spring-scheduling-3.1 #3993
- [x] spring/spring-web-3.1 #3731
- [x] spring/spring-webflux-5.0 #3798 
- [x] spring/spring-webmvc-3.1 #3132 #4258
- [x] spring/spring-ws-2.0 #3801
- [x] spymemcached-2.12 #4273
- [x] struts-2.3 #3835
- [x] tapestry-5.4 #3837
- [x] tomcat/tomcat-10.0 #4078
- [x] tomcat/tomcat-7.0 #4078
- [x] tomcat/tomcat-common #4078
- [x] twilio-6.6 #4045
- [x] undertow-1.4 #4239
- [x] vaadin-14.2 #4588
- [x] vertx-web-3.0 #4510

**Comment by dengliming** [comment]
methods [https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3070](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3070)
redisson-3.0 [https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3069](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3069)

**Comment by michaelbannister** [comment]
I intend to have a go at okhttp/okhttp-3.0 this week

**Comment by HaloFour** [comment]
I'll take a stab at converting `WithSpanAspect` under `spring-boot-autoconfigure`.

**Comment by shivanshu1333** [comment]
Hey everyone, I'll be working on `play/play-2.4` and `play/play-2.6` this week :)

**Comment by trask** [comment]
> Hey @iNikem, yes I'll raise PRs soon

@shivanshu1333 if you can send PR(s) by end of next week that would be great, otherwise let's give those two tasks back to the pool so someone else can pick them up 👍

**Comment by jamesmoessis** [comment]
🥳
