### ISSUE TITLE
Requirements for contrib instrumentations

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#3505]
This issue tracks all requirements/dependencies that we have to implement to be able to extract instrumentation to the contrib repo.

- [ ] Extract and publish the muzzle codegen plugin #2778
- [ ] Extract and publish the muzzle check plugin #1225
- [ ] Release stable `instrumentation-api` #2892
- [ ] Release stable `javaagent-instrumentation-api` (still called `javaagent-api` for now)
- [ ] Release stable `javaagent-extension-api`

It might be a good idea to stabilize at least a part of `testing-common` too, those instrumentations have to have tests after all.

**Comment by iNikem** [comment]
What about `instrumentation-api-annotation-support` and `instrumentation-api-caching`? Is making them stable required for proper contrib experience?

**Comment by mateuszrzeszutek** [comment]
`instrumentation-api-caching` is a part of `instrumentation-api` (it shouldn't be released at all, it's baked into the `instrumentation-api` lib) so it's required.
We probably don't have to make `instrumentation-api-annotation-support` stable yet, it's only used in those instrumentations that do something with annotations (e.g. `@WithSpan`)

**Comment by jaydeluca** [comment]
It looks like this work is completed, but if there's anything left, feel free to re-open.

we did publish `javaagent-instrumentation-api` for a while:

<img width="1213" height="616" alt="Image" src="https://github.com/user-attachments/assets/a48a7808-acd8-44ea-b789-5b181eb98307" />

And the extension api is available:

<img width="1245" height="551" alt="Image" src="https://github.com/user-attachments/assets/84f6fb19-038b-497e-aeb3-902bc6344c56" />
