### ISSUE TITLE
Bring back instrumentation that was commented out during the transition to OpenTelemetry API

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#50]
Some instrumentation was commented out during the transition to OpenTelemetry API (#51 and #12). We need to figure out a way to bring these back.

- [x] ~log4j1~ (work moved to #133)
- [x] ~log4j2~ (work moved to #133)
- [x] ~slf4j-mdc~ (work moved to #133)
- [x] kafka-streams-0.11 (resolved in #109)
- [x] aws-java-sdk-2.2 (resolved in #109)
- [x] rabbitmq (resolved in #109)
- [x] spring-webflux-5 (http client)

JAX-RS instrumentation was not commented out, but there was potentially some loss during the transition, as it previously used `getLocalRootSpan()` and now just uses the parent span, which makes all the same tests pass, but may have some impact in the real world.

- [ ] jax-rs-annotations-1
- [ ] jax-rs-annotations-2

**Comment by trask** [comment]
Finishing this should be straightforward once #465 is done

**Comment by trask** [comment]
Closing. The last two will be resolved by #575.
