### ISSUE TITLE
Help wanted! Convert Groovy tests to Java

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#7195]
We've made some initial progress in #7148, #6613, #6537, #6497, #6484, #6486, #6485, #5774, #5688, #5679, #5668, #5660, #5596, #5581, #5521, #5504, #5399, #3768, #3525 (among others)

But there's so much more! 😅

Pick your favorite(s) and help us convert one or two (or ten!)

- [x] apache-camel-2.20 #8813
- [x] apache-dubbo-2.7 #12008
- [x] apache-httpclient/apache-httpclient-2.0 #12102
- [x] apache-httpclient/apache-httpclient-4.0 #7912
- [x] async-http-client/async-http-client-1.9 #8954
- [x] async-http-client/async-http-client-2.0 #8954
- [x] aws-sdk/aws-sdk-1.11  #10657 #10660 #12606 #12755 #12777
- [x] aws-sdk/aws-sdk-2.2 #11240 #12895 #12949
- [x] cassandra/cassandra-3.0 #7390
- [x] cassandra/cassandra-4.0 #7390
- [x] couchbase/couchbase-2-common #9426
- [x] couchbase/couchbase-2.0 #12193
- [x] couchbase/couchbase-2.6 #12193
- [x] couchbase/couchbase-3.1 #10880
- [x] couchbase/couchbase-3.1.6 #12193
- [x] couchbase/couchbase-3.2 #8837
- [x] dropwizard/dropwizard-testing #12542 
- [x] dropwizard/dropwizard-views-0.7 #8808
- [x] elasticsearch/elasticsearch-rest-5.0 #8542
- [x] elasticsearch/elasticsearch-rest-6.4 #8524
- [x] elasticsearch/elasticsearch-rest-7.0 #8799
- [x] elasticsearch/elasticsearch-transport-5.0 #12300
- [x] elasticsearch/elasticsearch-transport-5.3 #12300
- [x] elasticsearch/elasticsearch-transport-6.0 #12300
- [x] external-annotations #9557
- [x] geode-1.4 #8141
- [x] grails-3.0
- [x] grizzly-2.0 #12248
- [x] gwt-2.0 #8201
- [x] hibernate/hibernate-3.3 #9025
- [x] hibernate/hibernate-4.0 #9211 #9249 #9282
- [x] hibernate/hibernate-6.0 #8304
- [x] hibernate/hibernate-procedure-call-4.3 #9290
- [x] http-url-connection #7676
- [x] hystrix-1.4  #9217
- [x] internal/internal-class-loader #9560 #12983
- [x] internal/internal-lambda #9611
- [x] internal/internal-reflection #9612
- [x] internal/internal-url-class-loader #9614
- [x] java-util-logging #7631
- [x] jaxrs/jaxrs-1.0 #12745
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-annotations #12816
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-cxf-3.2 #12816
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-jersey-2.0 #12816
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-resteasy-3.0 #12816
- [x] jaxrs/jaxrs-2.0/jaxrs-2.0-resteasy-3.1 #12816
- [x] jaxrs/jaxrs-3.0/jaxrs-3.0-annotations #12816
- [x] jaxrs/jaxrs-3.0/jaxrs-3.0-jersey-3.0 #12816
- [x] jaxrs/jaxrs-3.0/jaxrs-3.0-resteasy-6.0 #12816
- [x] jaxrs-client/jaxrs-client-1.1 #12497
- [x] jaxws/jaxws-2.0 #12509
- [x] jaxws/jaxws-2.0-axis2-1.6 #12509
- [x] jaxws/jaxws-2.0-cxf-3.0 #12509
- [x] jaxws/jaxws-2.0-metro-2.2 #12509
- [x] jaxws/jaxws-jws-api-1.1 #12509
- [x] jboss-logmanager/jboss-logmanager-appender-1.1 #7703
- [x] jboss-logmanager/jboss-logmanager-mdc-1.1 #7703
- [x] jdbc #11178 #12132
- [x] jedis/jedis-1.4 #7731
- [x] jedis/jedis-3.0 #7731
- [x] jedis/jedis-4.0 #7731
- [x] jetty/jetty-11.0 #7976
- [x] jetty/jetty-8.0 #7975
- [x] jetty-httpclient/jetty-httpclient-9.2 #9072
- [x] jms-1.1 #9476
- [x] jsf/jsf-mojarra-1.2 #11711
- [x] jsf/jsf-mojarra-3.0 #11694
- [x] jsf/jsf-myfaces-1.2 #11711
- [x] jsf/jsf-myfaces-3.0 #11694
- [x] jsp-2.3 #11827
- [x] kafka/kafka-clients/kafka-clients-0.11 #7770
- [x] kafka/kafka-streams-0.11 #12437
- [x] kubernetes-client-7.0 #9163
- [x] lettuce/lettuce-4.0 #9419
- [x] lettuce/lettuce-5.0 #9547
- [x] lettuce/lettuce-5.1 #9876 #9994 #1004
- [x] log4j/log4j-appender-1.2 #7631
- [x] log4j/log4j-appender-2.17 #7631
- [x] log4j/log4j-context-data/log4j-context-data-2.17 #9804
- [x] log4j/log4j-context-data/log4j-context-data-2.7 #9804
- [x] log4j/log4j-mdc-1.2 #8170
- [x] logback/logback-mdc-1.0 #9490
- [x] mongo/mongo-3.1 #12382
- [x] mongo/mongo-3.7 #12382
- [x] mongo/mongo-4.0 #12382
- [x] mongo/mongo-async-3.3 #12382
- [x] netty/netty-3.8 #7666
- [x] netty/netty-4.0 #9976
- [x] netty/netty-4.1 #12108
- [x] opentelemetry-api/opentelemetry-api-1.0 #12133
- [x] opentelemetry-extension-annotations-1.0
- [x] opentelemetry-instrumentation-annotations-1.16 #7781
- [x] play/play-mvc/play-mvc-2.4 #12271
- [x] play/play-mvc/play-mvc-2.6 #12340
- [x] play/play-ws/play-ws-1.0 #12377
- [x] play/play-ws/play-ws-2.0 #12377
- [x] play/play-ws/play-ws-2.1 #12377
- [x] rabbitmq-2.7 #9562
- [x] ratpack/ratpack-1.4 #12825
- [x] ratpack/ratpack-1.7 #12980 
- [x] reactor/reactor-netty/reactor-netty-0.9 #7635
- [x] rediscala-1.8 #12616
- [x] redisson/redisson-3.0 #9060
- [x] redisson/redisson-3.17 #9060
- [x] restlet/restlet-1.1 #12337
- [x] restlet/restlet-2.0 #12348
- [x] rocketmq/rocketmq-client/rocketmq-client-4.8 #10520
- [x] runtime-metrics #8928
- [x] rxjava/rxjava-2.0 #8397
- [x] rxjava/rxjava-3.0 #7924
- [x] rxjava/rxjava-3.1.1 #7924
- [x] servlet/servlet-2.2 #12013
- [x] servlet/servlet-3.0 #12013
- [x] servlet/servlet-5.0 #12364
- [x] spark-2.3 #8200
- [x] spring/spring-batch-3.0 #12004
- [x] spring/spring-core-2.0 #8166
- [x] spring/spring-data/spring-data-1.8 #8124
- [x] spring/spring-integration-4.1 #11999
- [x] spring/spring-jms/spring-jms-2.0 #11195
- [x] spring/spring-rabbit-1.0
- [x] spring/spring-rmi-4.0
- [x] spring/spring-scheduling-3.1 #9806
- [x] spring/spring-webflux-5.0 #9677
- [x] spring/spring-webmvc/spring-webmvc-3.1 #11114
- [x] spring/spring-webmvc/spring-webmvc-6.0 #11114
- [x] spring/spring-ws-2.0 #11196
- [x] spymemcached-2.12 #12368
- [x] struts-2.3 #11468
- [x] tapestry-5.4 #9684
- [x] tomcat/tomcat-10.0 #11420
- [x] tomcat/tomcat-7.0 #11402
- [x] twilio-6.6 #13077
- [x] undertow-1.4 #12207
- [X] vaadin-14.2 #7444
- [x] vertx/vertx-http-client/vertx-http-client-3.0 #10093
- [x] vertx/vertx-http-client/vertx-http-client-4.0 #13100
- [x] vertx/vertx-rx-java-3.5 #13117 
- [x] vertx/vertx-web-3.0 #12826
- [x] wicket-8.0 #9867

**Comment by AlexanderWert** [comment]
`elasticsearch/elasticsearch-rest-5.0` and `elasticsearch/elasticsearch-rest-6.4` already have Java tests.

Moved tests to Java for `elasticsearch/elasticsearch-rest-7.0` as part of this open PR:
- open-telemetry/opentelemetry-java-instrumentation#8799.

**Comment by jaydeluca** [comment]
I'm working on converting apache-camel-2.20

**Comment by jaydeluca** [comment]
it was a rainy day here, so I wrote a little script to track the progress of this project from the time this issue was opened

![example_output](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/7630696/47f00953-339e-4066-94a3-0b808b626f79)

**Comment by jaydeluca** [comment]
The issue has been open for about a year now, here's the latest progress report:

![latest](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/7630696/2ec01c3b-1dbf-4dac-a6e0-e7dd28e6ec76)

**Comment by zeitlinger** [comment]
Just tried both IDEA and copilot for converting, but neither was able to do it.

**Comment by jaydeluca** [comment]
in my travels I've come across a few that can be checked off in the checklist:
* elasticsearch/elasticsearch-rest-5.0 #8542 
* elasticsearch/elasticsearch-rest-6.4 #8524 
* elasticsearch/elasticsearch-rest-7.0 (i think this was always Java: #8911 )
* opentelemetry-extension-annotations-1.0 (I couldn't find a conversion PR for this one)

**Comment by jaydeluca** [comment]
Latest progress update:

<img src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/7630696/cc70f6df-aeb0-4b90-b76e-0f09a6132632" alt="progress" width=500>

**Comment by jaydeluca** [comment]
I found a few more that we can check off the list:

- [x] tomcat/tomcat-10.0 https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11420
- [x] tomcat/tomcat-7.0 https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11402
- [x] netty/netty-4.0 https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9976
- [x] spring/spring-jms/spring-jms-2.0 https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11195
- [x] rabbitmq-2.7 https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9562
- [x] spring/spring-rmi-4.0 (i'm not sure if there were ever groovy tests, wasn't able to find a PR)

**Comment by jaydeluca** [comment]
## Progress Update

We continue to burn down the groovy test files, and at the same time we can see further expansion of the java tests as more instrumentation is added:

<img src="https://github.com/user-attachments/assets/3010b1ef-e027-41fa-a687-6f6847c44929" alt="java vs groovy" width=500>

---

We are approaching the milestone of less than 300 remaining files, with over 250 files converted thus far:

<img src="https://github.com/user-attachments/assets/2167d85c-254e-43d1-beb0-b45e16584868" alt="groovy trend" width=500>

---

Here is a breakdown of the remaining instrumentation modules to be converted:


| Instrumentation               | Files to be converted |
|:------------------|------:|
| spring            |    52 |
| jaxrs             |    37 |
| servlet           |    23 |
| restlet           |    22 |
| couchbase         |    18 |
| aws-sdk           |    17 |
| ratpack           |    16 |
| elasticsearch     |    15 |
| play              |    15 |
| jaxws             |    15 |
| vertx             |    14 |
| mongo             |    10 |
| jdbc              |     8 |
| apache-dubbo-2.7  |     7 |
| jaxrs-client      |     5 |
| netty             |     5 |
| apache-httpclient |     3 |
| opentelemetry-api |     3 |
| grizzly-2.3       |     3 |
| grails-3.0        |     3 |
| undertow-1.4      |     3 |
| kafka             |     3 |
| internal          |     2 |
| dropwizard        |     2 |
| hibernate         |     1 |
| rediscala-1.8     |     1 |
| spymemcached-2.12 |     1 |
| twilio-6.6        |     1 |
| Total             |   305 |


<img src="https://github.com/user-attachments/assets/050ff485-24b0-4f2f-89e7-753260817a9a" alt="groovy breakdown" width=640>

**Comment by zeitlinger** [comment]
I'll give (some) spring tests a shot

**Comment by zeitlinger** [comment]
```
---------------------------------------------------------------------------------
Language                       files          blank        comment           code
---------------------------------------------------------------------------------
XSD                              406          27232           9758         293467
Java                            4065          46854          34176         248814
HTML                             553           1252           1580         152058
XML                             1181           1800           9778         126077
JSON                              62             50              0          92945
Kotlin                          1526          21083          59440          77275
Groovy                           361           6013           2643          33632
```

**Comment by laurit** [comment]
@zeitlinger I think you should exclude build directories

**Comment by zeitlinger** [comment]
good point 

```
~/opt/cloc-2.02/cloc --match-d='/(src)/' .
    4728 text files.
    4612 unique files.                                          
     118 files ignored.

github.com/AlDanial/cloc v 2.02  T=4.51 s (1021.5 files/s, 84070.5 lines/s)
---------------------------------------------------------------------------------
Language                       files          blank        comment           code
---------------------------------------------------------------------------------
Java                            3962          45180          33339         237806
Groovy                           360           5992           2323          33562
YAML                              16             44              5           6394
Scala                             34            399            213           2865
Kotlin                            39            481            288           2520
XML                               84            399             80           2158
JSON                               6             49              0           2091
Gradle                            24            294            355           1664
```

**Comment by jaydeluca** [comment]
we've got some serious momentum lately, and we're now below 200 files remaining. thanks @zeitlinger @laurit @shalk and @xiepuhuan!

<img src="https://github.com/user-attachments/assets/727ea342-682a-4c80-872e-5aba451abd5b" width=500 alt="test file burn down">


Remaining modules by file count percentage:

<img src="https://github.com/user-attachments/assets/8f22724f-1ac9-4316-9f73-7236c7ca3061" width=500 alt="breakdown">



instrumentation list sorted by sum of the file sizes:

| Key               |   File Count |  (Sum) File Size |
|:------------------|-------------:|------------------:|
| aws-sdk           |           17 |            127827 |
| jdbc              |            8 |             90890 |
| jaxrs             |           37 |             72352 |
| servlet           |           10 |             65662 |
| vertx             |           14 |             56845 |
| ratpack           |           16 |             51932 |
| mongo             |           10 |             51661 |
| play              |           15 |             48986 |
| restlet           |           22 |             38226 |
| jaxws             |           17 |             21595 |
| kafka             |            3 |             21505 |
| twilio-6.6        |            1 |             18936 |
| jaxrs-client      |            5 |             16067 |
| spymemcached-2.12 |            1 |             15630 |
| undertow-1.4      |            3 |             12754 |
| hibernate         |            1 |             12167 |
| dropwizard        |            2 |             10789 |
| rediscala-1.8     |            1 |              3898 |
| grails-3.0        |            3 |              3201 |
| internal          |            2 |              2603 |
| Total | 188 | 743526 |

**Comment by zeitlinger** [comment]
using cloc

```
---------------------------------------------------------------------------------
Language                       files          blank        comment           code
---------------------------------------------------------------------------------
Java                            4222          48133          34902         254323
Groovy                           234           3698           1488          21169
```

**Comment by jaydeluca** [comment]
the finish line is in sight, ~124 files left!

<img src="https://github.com/user-attachments/assets/75a07857-e556-4f14-a081-f8bafde869bc" width=500 alt="groovy timeseries">

<img src="https://github.com/user-attachments/assets/56cacab5-ac17-41da-a9cf-50b8e6495bc5" width=500 alt="groovy detailed">

| Key           |   File Count |   Total File Size |
|:--------------|-------------:|------------------:|
| aws-sdk       |           17 |            129822 |
| jaxrs         |           37 |             72352 |
| vertx         |           14 |             57034 |
| ratpack       |           16 |             55660 |
| jaxws         |           17 |             21595 |
| kafka         |            3 |             21493 |
| twilio-6.6    |            1 |             18936 |
| jaxrs-client  |            5 |             16067 |
| play          |            5 |             13988 |
| hibernate     |            1 |             12167 |
| dropwizard    |            2 |             10789 |
| rediscala-1.8 |            1 |              3898 |
| grails-3.0    |            3 |              3473 |
| internal      |            2 |              2603 |
| Total | 124 | 439877 |

**Comment by jaydeluca** [comment]
posting to avoid any duplicative work by others: I am completing the remaining aws sdk 1.11 tests

**Comment by shalk** [comment]
i will finish hibernate part

**Comment by zeitlinger** [comment]
`~/opt/cloc-2.02/cloc --match-d='/(src)/' instrumentation`

```
---------------------------------------------------------------------------------
Language                       files          blank        comment           code
---------------------------------------------------------------------------------
Java                            3679          40684          25995         222537
Groovy                            82           1138            438           8289
```

**Comment by jaydeluca** [comment]
We're now down to about 50 files 💪 

<img src="https://github.com/user-attachments/assets/a36d2ba6-0283-48c4-b8d3-ff6d8db24aae" alt="timeseries" width=500 />

<img src="https://github.com/user-attachments/assets/5e26ca93-00d9-4029-9528-edd92b2f1c84" alt="pie chart" width=500 />

| Key          |   File Count |   Total File Size |
|:-------------|-------------:|------------------:|
| aws-sdk      |            9 |             58624 |
| ratpack      |           20 |             58085 |
| vertx        |           14 |             57970 |
| twilio-6.6   |            1 |             18936 |
| jaxrs-client |            4 |             13629 |
| internal     |            2 |              2603 |
| Total | 50 | 209847 |

**Comment by jaydeluca** [comment]
I am currently working on aws 2.2 `AbstractAws2ClientCoreTest` and related tests

**Comment by shalk** [comment]
I will work on jaxrs-client and  twilio-6.6.

I think lib vertx-rx-java is write by scala. The test case should be convert to scala.

**Comment by jaydeluca** [comment]
Happy new year 🎉 ! We are quickly approaching the resolution of this effort. Here is the latest update:

We start 2025 with 22 files remaining (10 of which are already in code review):

<img src="https://github.com/user-attachments/assets/4e80e054-8352-4200-8659-3552b31a1ec5" alt="groovy timeseries" width=500 />

<br /><br />

Since most of these are already claimed or in code review, the vertx instrumentation makes up the majority of the remaining work:

<img src="https://github.com/user-attachments/assets/d50babb4-2cd1-4c57-b353-ccf9eed3b226" alt="groovy detailed" width=500 />


| Instrumentation          |   File Count |   Total File Size |
|:-------------|-------------:|------------------:|
| vertx        |           11 |             55030 |
| ratpack (in [code review](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12980))     |            4 |             25159 |
| twilio-6.6 (claimed by @shalk)  |            1 |             18936 |
| jaxrs-client (in [code review](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12903)) |            4 |             13629 |
| internal (in [code review](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12983))    |            2 |              2603 |
| Total | 22 | 115357 |

**Comment by jaydeluca** [comment]
whoa... we did it! nice work everyone!

**Comment by jaydeluca** [comment]
<img src='https://github.com/user-attachments/assets/900f9f79-ba41-4784-904c-f33bb10fd6ae' alt="burn down" width=600 />

**Comment by trask** [comment]
thanks to so many who contributed to this epic project! ❤

**Comment by tylerbenson** [comment]
Yay!  Great job finally finishing this.
